### PR TITLE
IndexPageTemplate Component Extraction

### PR DESCRIPTION
**Pull request by erikasmith-formidablelabs**
helloooo, it's been a minute 🤠 🌵 🕺 

the IndexPageTemplate component currently renders a bunch of components using data passed through from the config file. this PR explores the idea of pulling some of those components out of the oss-landers package altogether and instead defining them in the client and passing them through as children. 
we're doing this in an effort to transition to having `react-static` pass in the user’s config as route data (but if we do that it will be serialized, so any values that are react components won’t work).
this also gives the client the flexibility to pass in whatever they want to render on this page!

### CODE REVIEW

**Comment by erikasmith-formidablelabs** [comment]
@boygirl hi lauren :) I got started on some of the work we talked about a few weeks ago (description in PR) - I've only extracted the `Features` component so far, I wanted to get your eyes on this to make sure it's aligned with what you were envisioning. can you confirm before I take `Preview` & `Custom Section` out as well?

**Comment by boygirl** [comment]
@erikasmith-formidablelabs Good progress! I was imagining making the index page more flexible for library authors, but it would still be beneficial to provide some of the building blocks so that the styling remains as consistent as possible. The `Features` section should look the same between docs sites. What about exporting a `Features` component from the `formidable-oss-landers` library that library authors could use and provide with an array of feature objects.  Authors would still need to explicitly include it in their index page template. What do you think?

**Comment by erikasmith-formidablelabs** [comment]
@boygirl Ah yeah, that makes sense! I can play with this a bit :)

**Comment by erikasmith-formidablelabs** [comment]
@boygirl I think this should be ready to go based on our convo from a few weeks ago (we've left the Features, CustomSection, and Preview components in the library, and the user just has the option to pass them in as children)!

**Comment by boygirl** [comment]
@erikasmith-formidablelabs this all looks great! thanks for the changes!

**Review by boygirl — APPROVED** [review]

**Pull request merged**
